---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "development"
  DB_HOST: "postgresql-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "12345"
  DB_NAME: "postgres"
  DB_COLUMN_ID: "id"
  DB_COLUMN_TASK: "task"
  FEATURE_EDIT_TASK: "false"
  FEATURE_DELETE_TASK: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  API_URL: "http://localhost:3000"
  FEATURE_EDIT_TASK: "false"
  FEATURE_DELETE_TASK: "true"
  VITE_APP_VERSION: "1.8-a"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS main_table (
        id SERIAL PRIMARY KEY,
        task VARCHAR(255) NOT NULL
    );
