---
kind: Kustomization
resources:
  - prometheus/serviceaccount.yaml
  - prometheus/role.yaml
  - prometheus/rolebinding.yaml
  - prometheus/configmap.yaml
  - prometheus/service.yaml
  - prometheus/statefulset.yaml
  - node-exporter/clusterrole.yaml
  - node-exporter/clusterrolebinding.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  - node-exporter/serviceaccount.yaml
  - kube-state-metrics/clusterrole.yaml
  - kube-state-metrics/clusterrolebinding.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - kube-state-metrics/serviceaccount.yaml
