# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
    - name: postgresql-db-service
      protocol: TCP
      port: 5432
      targetPort: 5432
---
