kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-app-cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443 # default
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
  - role: worker
  - role: worker
