---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
        - name: task-image
          image: galihhhp/elysia-backend:1.5-a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
