# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-backend
  type: ClusterIP
  ports:
    - name: task-backend-service
      protocol: TCP
      port: 3000
      targetPort: 3000
---
